[[main]]
  name = "Home"
  url = ""
  weight = -110

[[main]]
  name = "About"
  url = "about/"
  weight = -109

# social menu links

[[social]]
  name = "github"
  type = "social"
  weight = 1
  url = "https://github.com/rwaal"
[[social]]
  name = "twitter"
  weight = 2
  url = "https://twitter.com/rwaal"
[[social]]
  name = "linkedin"
  weight = 3
  url = "https://www.linkedin.com/in/richardwaal"
[[social]]
  name = "rss"
  weight = 4
  url = "index.xml"
